FINANCE_DATA = "ФИНАНСОВЫЕ ДАННЫЕ (карты)"
SECRET_DATA = "СЕКРЕТНЫЕ КЛЮЧИ (API-ключи и пароли)"
SYSTEM_INFO = "СИСТЕМНАЯ ИНФОРМАЦИЯ"
DECODED_MESS = "РАСШИФРОВАННЫЕ СООБЩЕНИЯ"
SAFETY_ALERT = "УГРОЗЫ БЕЗОПАСНОСТИ"
NORMALIZED_DATA = "НОРМАЛИЗОВАННЫЕ ДАННЫЕ"
